### ISSUE TITLE
lib/codemirror.css seems out of date in new releases

### ISSUE THREAD

**Issue by akdor1154** [components/codemirror#3]
Heya,
Looks like `lib/codemirror.css` does not match source in CodeMirror repo from 5.54 onwards. Unsure if this repo is manually maintained or autopublished or what...

Jarrad

**Comment by akdor1154** [comment]
Running `component-tools/build.sh 5.55.0` gives me a properly tagged and updated 5.55.0 version with proper lib/codemirror.css... so I have nfi what is going on. @minrk?

**Comment by RobLoach** [comment]
If you shoot up a pull request, we can have it merged. Thanks!

**Comment by akdor1154** [comment]
I don't think it's as simple as that - the only thing I can change with a PR is the master branch, and that has nothing to do with releases. Your releases are based on git tags, which I cannot change with a pull request.

I don't know what your protocol is for re-releasing a changed bower version for an unchanged upstream - e.g. here, bower 5.55.0 is an incorrectly built package of upstream 5.55.0. Do you want to silently fix the contents of the bower tag? (This requires push access to the repo.) Or maybe the protocol is to add a suffix to the release, linux distro style, e.g. 5.55.0~bower1? Or something else?

**Comment by akdor1154** [comment]
So I found the issue in the build script that caused this and raise a PR at #4 . Unfortunately though, merging that will not be sufficient to fix the broken releases that were caused as a result of the bug.

**Comment by RobLoach** [comment]
Added you to the repo :wink: 

We could do a `5.55.0~bower1` .... That makes sense to me.

**Comment by akdor1154** [comment]
reading up on it, that is invalid semver. Do you know how Bower treats "+build" suffixes? By the semver spec it's meant to ignore them with respect to precedence. But I know next to nothing about Bower. If it takes them into account then you could release 5.55.0+bower1.

**Comment by RobLoach** [comment]
`5.55.0-fixed1` perhaps?

**Comment by RobLoach** [comment]
Unsure about Bower, but in npm, you can target tags like that.

**Comment by akdor1154** [comment]
Semver spec says `-label` is for a prerelease, e.g. `-rc0`, I don't think that's quite right.

I am tempted to just point the tags at new commits if you're comfortable with that, as well as add some `+bower1` tags to allow downstreams to force depending on a fixed version. This means new installs from consumers will get the fixed versions. It will not prompt updates if these versions are installed in existing downstreams, but I don't think there is a way to do that without trampling on upstream codemirror's versioning. (e.g. releasing bower tag 5.56.1 and hoping that upstream codemirror never releases a 5.56.1)

Ugh, semver is going firmly on the list of "poor js-land implementations of things that Debian solved properly decades ago".

**Comment by RobLoach** [comment]
Could do our own `5.56.1-alpha1`.... Even though it's not technically .1, meh?

**Comment by akdor1154** [comment]
That would be valid, but it wouldn't solve getting existing installs to auto-update. (as per semver, `-label` will never be installed by default as it is designed for pre-releases).

**Comment by akdor1154** [comment]
for now I will publish `+components1` re-releases of tags > 5.53.0. I'm not confident enough to silently republish under the same versions, this feels naughty. Codemirror seem to do releases fast enough that .57 should be out soon.

**Comment by akdor1154** [comment]
This is now done so I'll close this issue. I made a small change to the build script to do it which is backwards compatible, I've left that PR open for review to leave some hint as to wtf happened when @minrk builds the next release :)

**Comment by RobLoach** [comment]
Thanks so much for all the help here! :muscle:

**Comment by akdor1154** [comment]
no worries, you too!
